Asking researchers for information about completed but never published studies has not always been found to be fruitful (Hetherington et al 1989, Horton 1997) though some researchers have reported that this is an important method for retrieving studies for systematic reviews (Royle and Milne 2003, Greenhalgh and Peacock 2005, Reveiz et al 2006). The R1AT (Restoring Invisible and Abandoned Trials) initiative (Doshi et al 2013) aims to address these problems by offering a methodology that allows others to re-publish mis-reported and to publish unreported trials. Anyone who can access the trial data and document trial abandonment can use this methodology. The R1AT Support Centre offers free-of-charge support and competitive funding to researchers interested in this approach. It has been suggested that legislation such as Freedom of Information Acts in various countries might be used to gain access to information about unpublished trials (Bennett and Jull 2003, MacLean et al 2003).

#### 4.3.3 Trials registers and trials results registers

A recent study suggested that trials registers are an important source for identifying additional randomized trials (Baudard et al 2017). Cochrane Reviews of interventions should search relevant trials registers and repositories of results (see MECIR Box 4.3.d). Although there are many other trials registers, ClinicalTrials.gov and the WHO International Clinical Trials Registry Platform (ICTRP) portal (Pansieri et al 2017) are considered to be the most important for searching to identify studies for a systematic review. Research has shown that even though ClinicalTrials.gov is included in the WHO ICTRP Search Portal, not all ClinicalTrials.gov records can be successfully retrieved via searches of the ICTRP Search Portal (Glanville et al 2014, Knelangen et al 2018). Therefore, it is not sufficient to search the ICTRP alone. Guidance for searching these and other trials registers is provided in the online Technical Supplement.

In addition to Cochrane, other organizations such as the Agency for Healthcare Research and Quality (AHRQ) (Agency for Healthcare Research and Quality 2014) and the US Institute of Medicine (Institute of Medicine 2011) also advocate searching trials registers.

[backgroundcolor=gray!20, linecolor=gray!There has been an increasing acceptance by investigators of the importance of registering trials at inception and providing access to their trials results. Despite perceptions and even assertions to the contrary, however, there is no global, universal legal requirement to register clinical trials at inception or at any other stage in the process, although some countries are beginning to introduce such legislation (Viergever and Li 2015).

Efforts have been made by a number of organizations, including organizations representing the pharmaceutical industry and individual pharmaceutical companies, to begin to provide central access to ongoing trials and in some cases trial results on completion, either on a national or international basis. A recent audit of pharmaceutical companies' policies on access to trial data, results and methods, however, showed that the commitments made by companies to transparency of trials were highly variable (Goldacre et al 2017). Increasingly, as already noted, trials registers such as ClinicalTrials.gov also contain the results of completed trials, not just simply listing the details of the trial.

#### 4.3.4 Regulatory agency sources and clinical study reports

Potentially relevant regulatory agency sources include the EU Clinical Trials Register, Drugs@FDA and OpenTrialSFDA. Details of these are provided in the online Technical Supplement. Clinical study reports (CSRs) are the reports of clinical trials providing detailed information on the methods and results of clinical trials submitted in support of marketing authorization applications. In late 2010, the European Medicines Agency (EMA) began releasing CSRs (on request) under their Policy 0043. In October 2016, they began to release CSRs under their Policy 0070. The policy applies only to documents received since 1 January 2015. The terms of use for access are based on the purposes to which the clinical data will be put.

A recent study by Jefferson and colleagues (Jefferson et al 2018) that looked at use of regulatory documents in Cochrane Reviews, found that understanding within the Cochrane community was limited and guidance and support would be required if review authors were to engage with regulatory documents as a source of evidence. Specifically, guidance on how to use data from regulatory sources is needed. For more information about using CSRs, see the online Technical Supplement. Further guidance on collecting data from CSRs is provided in Chapter 5, Section 5.5.6.

#### 4.3.5 Other sources

The online Technical Supplement describes several other important sources of reports of studies. The term 'grey literature' is often used to refer to reports published outside of traditional commercial publishing. Review authors should generally search sources such as dissertations and conference abstracts (see MECIR Box 4.3.e).

Review authors may also consider searching the internet, handsearching of journals and searching full texts of journals electronically where available (see online Technical Supplement for details). They should examine previous reviews on the same topic and check reference lists of included studies and relevant systematic reviews (see MECIR Box 4.3.e).